name: Mex build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Matlab
      run: |
        Invoke-WebRequest -Uri https://www.mathworks.com/mpm/win64/mpm -OutFile mpm.exe