name: Mex build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  MATLAB_VERSION: R2022b

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup up MSVC dev cmd
      uses: ilammy/msvc-dev-cmd@v1
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.29.x'
    - name: Setup Matlab
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{ env.MATLAB_VERSION }}
    - name: Configure
      run: |
        cmake --preset windows-msvc-release-config -DBUILD_TESTS=OFF
      working-directory: ${{ github.workspace }}
    - name: Build
      run: |
        cmake --build --preset windows-msvc-release-build --target install
      working-directory: ${{ github.workspace }}
    - uses: actions/upload-artifact@v4
      with:
        name: windows
        path: out/install/windows-msvc-release-config/mex/*mex*
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: out/install/windows-msvc-release-config/mex/*mex*
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.29.x'
    - name: Setup Matlab
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{ env.MATLAB_VERSION }}
    - name: Configure
      run: |
        cmake --preset linux-gcc-release-config -DBUILD_TESTS=OFF
      working-directory: ${{ github.workspace }}
    - name: Build
      run: |
        cmake --build --preset linux-gcc-release-build --target install
      working-directory: ${{ github.workspace }}
    - uses: actions/upload-artifact@v4
      with:
        name: linux
        path: out/install/linux-gcc-release-config/mex/*mex*
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: out/install/linux-gcc-release-config/mex/*mex*

  maci:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.29.x'
    - name: Install Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Setup Matlab
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{ env.MATLAB_VERSION }}
    - name: Configure
      run: |
        brew install automake
        cmake --preset macos-gcc-release-config -DBUILD_TESTS=OFF
      working-directory: ${{ github.workspace }}
    - name: Build
      run: |
        cmake --build --preset macos-gcc-release-build --target install
      working-directory: ${{ github.workspace }}
    - uses: actions/upload-artifact@v4
      with:
        name: maci
        path: out/install/macos-gcc-release-config/mex/*mex*
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: out/install/macos-gcc-release-config/mex/*mex*